export HOME="/home/vscode"
export ZSH="$HOME/.oh-my-zsh"

# Dynamically set Homebrew path based on architecture
if [ -d "/home/linuxbrew/.linuxbrew" ]; then
    export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
elif [ -d "/opt/homebrew" ]; then
    export PATH="$PATH:/opt/homebrew/bin"
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

ZSH_THEME="agnoster"

zstyle ':omz:update' mode auto  

DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
        git 
        git-auto-fetch
        brew 
        command-not-found 
        cp 
        docker 
        direnv 
        dirhistory 
        kubectl 
        microk8s 
        extract 
        npm 
        zsh-interactive-cd 
        zsh-syntax-highlighting 
        zsh-autosuggestions 
    )

source $ZSH/plugins/zsh-interactive-cd/zsh-interactive-cd.plugin.zsh
source $ZSH/oh-my-zsh.sh

alias hgrep="history | grep"


eval "$(starship init zsh)"
